### ISSUE TITLE
nginx: [emerg]

### ISSUE THREAD

**Issue by extensionsapp** [mariusv/nginx-badbot-blocker#154]
Hello.

```
Aug 25 23:21:57 ziggo systemd[1]: Starting LSB: Stop/start nginx...
Aug 25 23:21:57 ziggo nginx[11876]: nginx: [emerg] unexpected "}" in /etc/nginx/conf.d/test.conf:140
Aug 25 23:21:57 ziggo systemd[1]: nginx.service: control process exited, code=exited status=1
Aug 25 23:21:57 ziggo systemd[1]: Failed to start LSB: Stop/start nginx.
Aug 25 23:21:57 ziggo systemd[1]: Unit nginx.service entered failed state.
```

Fix your tutorial.

```
#			include /etc/nginx/bots.d/blockbots.conf
#			include /etc/nginx/bots.d/ddos.conf
```

to

```
#			include /etc/nginx/bots.d/blockbots.conf;
#			include /etc/nginx/bots.d/ddos.conf;
```

**Comment by mitchellkrogza** [comment]
Please see Step :5 there is nothing wrong with the syntax or tutorial.

## 5:

**ADD INCLUDE FILES INTO A VHOST**

Open a site config file for Nginx (just one for now) and add the following lines.

##### VERY IMPORTANT NOTE: 

These includes MUST be added within a **server {}** block of a vhost otherwise you will get EMERG errors from Nginx.

- `include /etc/nginx/bots.d/blockbots.conf;`

- `include /etc/nginx/bots.d/ddos.conf;`

**Comment by extensionsapp** [comment]
https://github.com/mariusv/nginx-badbot-blocker/blob/master/VERSION_2/conf.d/blacklist.conf#L64
https://github.com/mariusv/nginx-badbot-blocker/blob/master/VERSION_2/bots.d/blockbots.conf#L7
https://github.com/mariusv/nginx-badbot-blocker/blob/master/VERSION_2/bots.d/ddos.conf#L7

<img width="377" alt="screenshot_6" src="https://user-images.githubusercontent.com/8192379/29740707-276ede6c-8a65-11e7-901d-ba463daf7eaa.png">

**Comment by mitchellkrogza** [comment]
Ahh, thanks, I will fix now. Apologies.

**Comment by mitchellkrogza** [comment]
@extensionsapp fixed in latest commit. Thanks for picking up on that. 👍
